import { Subject, Lab, Channel, Announcement, Material, Poll, EventItem, Deadline, Profile } from './types'

export const MOCK_USER: Profile = {
  id: 'user-demo-admin-1',
  username: 'alex_dev',
  display_name: 'Alex Rivera',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  bio: 'IT Student & Class Rep | Tech Enthusiast',
  role: 'admin',
  created_at: new Date().toISOString(),
}

export const MOCK_SUBJECTS: Subject[] = [
  { id: 'sub-1', code: '101BS', name: 'Mathematics - I', semester: 1, sort_order: 1, created_at: new Date().toISOString() },
  { id: 'sub-2', code: '104BS', name: 'Semiconductor Physics', semester: 1, sort_order: 2, created_at: new Date().toISOString() },
  { id: 'sub-3', code: '110ES', name: 'Basic Electrical Engineering', semester: 1, sort_order: 3, created_at: new Date().toISOString() },
  { id: 'sub-4', code: '119ES', name: 'Fundamentals of Programming', semester: 1, sort_order: 4, created_at: new Date().toISOString() },
  { id: 'sub-5', code: '114ES', name: 'IT Essentials Workshop', semester: 1, sort_order: 5, created_at: new Date().toISOString() },
  { id: 'sub-6', code: '121HS', name: 'Environmental Science', semester: 1, sort_order: 6, created_at: new Date().toISOString() },
]

export const MOCK_LABS: Lab[] = [
  { id: 'lab-104-1', subject_id: 'sub-2', name: 'Crystal Structure & Miller Indices', sort_order: 1, created_at: new Date().toISOString() },
  { id: 'lab-104-2', subject_id: 'sub-2', name: 'Quantum Mechanics — de Broglie', sort_order: 2, created_at: new Date().toISOString() },
  { id: 'lab-110-1', subject_id: 'sub-3', name: 'DC Circuits — KVL & KCL', sort_order: 1, created_at: new Date().toISOString() },
  { id: 'lab-119-1', subject_id: 'sub-4', name: 'Lab 1 — Algorithm Design & Pseudocode', sort_order: 1, created_at: new Date().toISOString() },
  { id: 'lab-119-2', subject_id: 'sub-4', name: 'Lab 2 — C Basics & Operators', sort_order: 2, created_at: new Date().toISOString() },
  { id: 'lab-119-3', subject_id: 'sub-4', name: 'Lab 3 — Control Structures & Loops', sort_order: 3, created_at: new Date().toISOString() },
  { id: 'lab-114-1', subject_id: 'sub-5', name: 'Workshop 1 — Computer Hardware & Software', sort_order: 1, created_at: new Date().toISOString() },
]

export const MOCK_CHANNELS: Channel[] = [
  { id: 'chan-gen', name: 'general', description: 'General class discussion', subject_id: null, is_default: true, created_at: new Date().toISOString() },
  { id: 'chan-off', name: 'off-topic', description: 'Anything goes', subject_id: null, is_default: true, created_at: new Date().toISOString() },
  { id: 'chan-res', name: 'resources', description: 'Share links, tips, and tools', subject_id: null, is_default: true, created_at: new Date().toISOString() },
  { id: 'chan-101bs', name: '101bs', description: 'Mathematics - I subject discussion', subject_id: 'sub-1', is_default: false, created_at: new Date().toISOString() },
  { id: 'chan-104bs', name: '104bs', description: 'Semiconductor Physics discussion', subject_id: 'sub-2', is_default: false, created_at: new Date().toISOString() },
  { id: 'chan-110es', name: '110es', description: 'Basic Electrical Engineering discussion', subject_id: 'sub-3', is_default: false, created_at: new Date().toISOString() },
  { id: 'chan-119es', name: '119es', description: 'Fundamentals of Programming discussion', subject_id: 'sub-4', is_default: false, created_at: new Date().toISOString() },
  { id: 'chan-114es', name: '114es', description: 'IT Essentials Workshop discussion', subject_id: 'sub-5', is_default: false, created_at: new Date().toISOString() },
  { id: 'chan-121hs', name: '121hs', description: 'Environmental Science discussion', subject_id: 'sub-6', is_default: false, created_at: new Date().toISOString() },
]

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: '🚀 ClassmateHub is Live for IT Semester 1!',
    content: 'Welcome everyone! Access syllabus notes, lab code templates, study guides, and live class discussions right here. Make sure to check out the shared deadlines board.',
    is_pinned: true,
    created_by: 'user-demo-admin-1',
    expires_at: null,
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    profiles: MOCK_USER,
  },
  {
    id: 'ann-2',
    title: '📢 Mid-Semester Exam Schedule Released',
    content: 'Mid-semester tests will start next Monday. Please review the updated deadline calendar under the Deadlines section.',
    is_pinned: true,
    created_by: 'user-demo-admin-1',
    expires_at: null,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    profiles: MOCK_USER,
  },
]

export const MOCK_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    title: 'C Programming Lab 3 — Solutions & Flowcharts',
    description: 'Complete solution guide for Lab 3 covering nested loops, switch statements, and pattern printing.',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_key: 'demo/lab3_c.pdf',
    file_name: 'lab3_c_solutions.pdf',
    file_type: 'pdf',
    file_size_bytes: 2450000,
    video_url: null,
    subject_id: 'sub-4',
    lab_id: 'lab-119-3',
    tags: ['c', 'loops', 'solutions'],
    uploaded_by: 'user-demo-admin-1',
    sort_order: 1,
    is_hidden: false,
    download_count: 42,
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    profiles: MOCK_USER,
    subjects: MOCK_SUBJECTS[3],
    labs: MOCK_LABS[5],
  },
  {
    id: 'mat-2',
    title: 'Semiconductor Physics — Unit 1 Miller Indices Guide',
    description: 'Detailed explanation of crystal planes, Miller indices calculations, and example problems.',
    file_url: null,
    file_key: null,
    file_name: null,
    file_type: 'video',
    file_size_bytes: null,
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    subject_id: 'sub-2',
    lab_id: 'lab-104-1',
    tags: ['physics', 'miller-indices', 'video-lecture'],
    uploaded_by: 'user-demo-admin-1',
    sort_order: 2,
    is_hidden: false,
    download_count: 18,
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    profiles: MOCK_USER,
    subjects: MOCK_SUBJECTS[1],
    labs: MOCK_LABS[0],
  },
  {
    id: 'mat-3',
    title: 'Basic Electrical Engineering — Circuit Analysis Cheat Sheet',
    description: 'Formula summary sheet for KVL, KCL, Nodal Analysis, and Star-Delta conversions.',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_key: 'demo/electrical_cheatsheet.pdf',
    file_name: 'electrical_formulas.pdf',
    file_type: 'pdf',
    file_size_bytes: 1850000,
    video_url: null,
    subject_id: 'sub-3',
    lab_id: 'lab-110-1',
    tags: ['electrical', 'formulas', 'kvl-kcl'],
    uploaded_by: 'user-demo-admin-1',
    sort_order: 3,
    is_hidden: false,
    download_count: 65,
    created_at: new Date(Date.now() - 3600000 * 30).toISOString(),
    profiles: MOCK_USER,
    subjects: MOCK_SUBJECTS[2],
    labs: MOCK_LABS[2],
  },
  {
    id: 'mat-4',
    title: 'IT Workshop 1 — OS Installation Commands Script',
    description: 'Bash and PowerShell script examples for initial Linux setup and basic package installs.',
    file_url: 'https://raw.githubusercontent.com/torvalds/linux/master/README',
    file_key: 'demo/setup.sh',
    file_name: 'setup_script.sh',
    file_type: 'code',
    file_size_bytes: 42000,
    video_url: null,
    subject_id: 'sub-5',
    lab_id: 'lab-114-1',
    tags: ['linux', 'bash', 'workshop'],
    uploaded_by: 'user-demo-admin-1',
    sort_order: 4,
    is_hidden: false,
    download_count: 29,
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    profiles: MOCK_USER,
    subjects: MOCK_SUBJECTS[4],
    labs: MOCK_LABS[6],
  },
]

export const MOCK_POLLS: Poll[] = [
  {
    id: 'poll-1',
    question: 'When should we schedule the Math-1 Group Study Session for Mid-Terms?',
    options: ['Saturday 4:00 PM', 'Sunday 10:00 AM', 'Sunday 3:00 PM', 'Monday Evening'],
    allow_multiple: false,
    is_anonymous: false,
    created_by: 'user-demo-admin-1',
    expires_at: new Date(Date.now() + 3600000 * 72).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 10).toISOString(),
    profiles: MOCK_USER,
    votes_count: { 0: 12, 1: 24, 2: 8, 3: 5 },
    total_votes: 49,
    user_voted_options: [1],
  },
  {
    id: 'poll-2',
    question: 'Which programming language do you want a supplementary workshop on?',
    options: ['Python Data Structures', 'C Deep-Dive Pointers', 'Web Dev (HTML/CSS/JS)', 'Git & GitHub Basics'],
    allow_multiple: true,
    is_anonymous: true,
    created_by: 'user-demo-admin-1',
    expires_at: new Date(Date.now() + 3600000 * 120).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 20).toISOString(),
    profiles: MOCK_USER,
    votes_count: { 0: 31, 1: 18, 2: 45, 3: 28 },
    total_votes: 122,
    user_voted_options: [0, 2],
  },
]

export const MOCK_EVENTS: EventItem[] = [
  {
    id: 'evt-1',
    title: 'C Programming Lab 4 Group Prep',
    description: 'Review arrays, string operations, and practice pointer questions for the upcoming lab evaluation.',
    type: 'study_session',
    location: 'Lab Room 204 & Google Meet',
    start_time: new Date(Date.now() + 3600000 * 28).toISOString(),
    end_time: new Date(Date.now() + 3600000 * 30).toISOString(),
    max_attendees: 30,
    subject_id: 'sub-4',
    created_by: 'user-demo-admin-1',
    created_at: new Date().toISOString(),
    profiles: MOCK_USER,
    subjects: MOCK_SUBJECTS[3],
    user_rsvp_status: 'going',
    going_count: 18,
    maybe_count: 5,
  },
  {
    id: 'evt-2',
    title: 'Git & Linux Essentials Workshop',
    description: 'Hands-on training session covering Git commits, branching, remote repositories, and command line efficiency.',
    type: 'workshop',
    location: 'BVM IT Department Seminar Hall',
    start_time: new Date(Date.now() + 3600000 * 72).toISOString(),
    end_time: new Date(Date.now() + 3600000 * 75).toISOString(),
    max_attendees: 60,
    subject_id: 'sub-5',
    created_by: 'user-demo-admin-1',
    created_at: new Date().toISOString(),
    profiles: MOCK_USER,
    subjects: MOCK_SUBJECTS[4],
    user_rsvp_status: 'maybe',
    going_count: 32,
    maybe_count: 12,
  },
]

export const MOCK_DEADLINES: Deadline[] = [
  {
    id: 'dl-1',
    title: 'C Programming Assignment 2 — Control Structures',
    description: 'Submit written code for 10 problems on loop optimization and nested conditionals.',
    subject_id: 'sub-4',
    due_date: new Date(Date.now() + 3600000 * 36).toISOString(),
    type: 'assignment',
    created_by: 'user-demo-admin-1',
    created_at: new Date().toISOString(),
    subjects: MOCK_SUBJECTS[3],
  },
  {
    id: 'dl-2',
    title: 'Electrical Engineering Lab Report #3',
    description: 'Submit verified KVL/KCL experiment calculations and graph printouts.',
    subject_id: 'sub-3',
    due_date: new Date(Date.now() + 3600000 * 96).toISOString(),
    type: 'lab',
    created_by: 'user-demo-admin-1',
    created_at: new Date().toISOString(),
    subjects: MOCK_SUBJECTS[2],
  },
  {
    id: 'dl-3',
    title: 'Semiconductor Physics Mid-Term Exam',
    description: 'Covers Units 1 to 3: Crystal structure, Miller indices, Quantum mechanics, and Diode I-V.',
    subject_id: 'sub-2',
    due_date: new Date(Date.now() + 3600000 * 168).toISOString(),
    type: 'exam',
    created_by: 'user-demo-admin-1',
    created_at: new Date().toISOString(),
    subjects: MOCK_SUBJECTS[1],
  },
]
